### PR TITLE
Show help when no command was specified.

### PR DESCRIPTION
**Pull request by jpopelka**
Previously it failed with:
`AttributeError: 'Namespace' object has no attribute 'func'`

### CODE REVIEW

**Comment by cgwalters** [comment]
bot, test pull request

**Comment by jlebon** [comment]
bot, retest this please

**Comment by rhatdan** [comment]
This works fine in atomic-1.6

**Comment by jpopelka** [comment]
> This works fine in atomic-1.6

I don't think so:
```
# atomic
Traceback (most recent call last):
  File "/usr/bin/atomic", line 433, in <module>
    sys.exit(args.func())
AttributeError: 'Namespace' object has no attribute 'func'
[root@localhost ~]# rpm -q atomic
atomic-1.6-5.git09ac479.fc23.x86_64
```

**Comment by rhatdan** [comment]
Ok it works on python2 but blows up with python3

**Comment by rhatdan** [comment]
Fixed in atomic-1.7
